version: 2
updates:
  # Update GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - github-actions
  commit-message:
    prefix: chore(deps)

  # Update Python dependencies via pip
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  commit-message:
    prefix: chore(deps)
  groups:
      # Group dev dependencies together
    dev-dependencies:
      patterns:
      - pytest*
      - ruff
      - mypy
      - pre-commit
      - bandit*
      update-types:
      - minor
      - patch
      # Group production dependencies
    production-dependencies:
      patterns:
      - '*'
      exclude-patterns:
      - pytest*
      - ruff
      - mypy
      - pre-commit
      - bandit*
      update-types:
      - minor
      - patch
