repos:
  # Pre-commit hooks for basic file checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-docstring-first
  - id: debug-statements
  - id: name-tests-test
    args: [--pytest-test-first]

  # Ruff - Fast Python linter and formatter (replaces flake8, isort, etc.)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.4
  hooks:
      # Run the linter
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
    exclude: ^scripts/
      # Run the formatter
  - id: ruff-format
    exclude: ^scripts/

  # Type checking with mypy (disabled for now - enable when ready to fix type issues)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: []
  #       args: ['--ignore-missing-imports']
  #       exclude: '^scripts/'

  # Security checks
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['bandit[toml]']

  # Markdown linting
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.42.0
  hooks:
  - id: markdownlint
    args: [--fix, --disable, MD013]            # Disable line-length rule

  # YAML formatting
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

# Global configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
